type Note {
  id: ID!
  name: String!
  completed: Boolean!
}

type Query {
  note(id: String!): Note!
  notes: [Note!]!
}

input CreateNoteInput {
  id: ID!
  name: String!
  completed: Boolean!
}

input UpdateNoteInput {
  id: ID!
  name: String!
  completed: Boolean!
}

type Mutation {
  createNote(in: CreateNoteInput!): Note
  updateNote(in: UpdateNoteInput!): Note
  deleteNote(id: String!): String
}

type Subscription {
  onCreateNote: Note @aws_subscribe(mutations: ["createNote"])
  onDeleteNote: String @aws_subscribe(mutations: ["deleteNote"])
  onUpdateNote: Note @aws_subscribe(mutations: ["updateNote"])
}
