type Note {
  id: ID!
  name: String!
  completed: Boolean!
}

type Query {
  note(id: String!): Note
  notes: [Note!]!
}

input CreateNoteInput {
  id: ID!
  name: String!
  completed: Boolean!
}

type Mutation {
  createNote(in: CreateNoteInput!): Note
  deleteNote(id: String!): String
}
