name: Test
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: yarn test
      - run: yarn build
